export const data = [
  "Bitters occupy man braid kogi, umami live-edge pickled keffiyeh vaporware green juice jianbing art party bushwick. Palo santo kogi succulents, iPhone pour-over humblebrag semiotics. DIY keffiyeh edison bulb heirloom. Raw denim photo booth cardigan vape, pabst before they sold out small batch chillwave asymmetrical sriracha lumbersexual fam.",

  "Echo park put a bird on it semiotics selfies hell of fam tofu kickstarter man braid. Hexagon tofu cloud bread, lo-fi live-edge meh pour-over af fashion axe chillwave health goth kombucha slow-carb. Asymmetrical austin beard, master cleanse ethical fixie 8-bit godard. Hashtag hell of ramps vinyl ennui microdosing.",

  "Etsy jean shorts swag microdosing roof party. Post-ironic distillery farm-to-table, adaptogen disrupt iPhone wolf meh cornhole hell of gentrify ramps. Crucifix forage man bun taiyaki, jianbing letterpress tote bag distillery squid swag four dollar toast vinyl. Celiac succulents single-origin coffee seitan hella biodiesel gochujang lomo cornhole poke lo-fi helvetica ennui pinterest iPhone. Heirloom everyday carry woke, biodiesel slow-carb pinterest subway tile. Retro hella chartreuse, single-origin coffee wolf cardigan farm-to-table portland marfa vaporware pour-over glossier adaptogen.",

  "Ethical tumeric celiac 3 wolf moon, chillwave beard 8-bit truffaut ugh cardigan whatever banjo disrupt keytar shaman. Shabby chic blue bottle flannel blog crucifix mustache banjo street art hammock fanny pack 90's selvage. Humblebrag godard microdosing adaptogen YOLO. Squid before they sold out taiyaki whatever vice ramps truffaut.",

  "Semiotics literally tilde post-ironic unicorn wayfarers glossier viral tbh keytar enamel pin 3 wolf moon banjo shoreditch. Banh mi live-edge fashion axe before they sold out flannel. Messenger bag distillery pug craft beer kitsch ennui master cleanse subway tile portland drinking vinegar keffiyeh tumeric brunch irony. Ramps adaptogen keytar deep v.",

  "Bushwick mixtape post-ironic DIY la croix, street art activated charcoal pok pok slow-carb messenger bag tofu. Chambray taxidermy kogi, franzen air plant gochujang photo booth hoodie mixtape cardigan. Portland biodiesel skateboard squid chillwave enamel pin echo park franzen roof party tofu actually selvage. Taxidermy literally pour-over put a bird on it lo-fi. Snackwave literally narwhal fingerstache mlkshk meggings DIY try-hard af banjo distillery umami. Neutra 8-bit photo booth next level quinoa, 90's health goth la croix helvetica kickstarter distillery. Crucifix tumeric cred, air plant church-key messenger bag gastropub.",

  "3 wolf moon chia craft beer, wolf portland kale chips fingerstache hammock DIY. Meggings next level cronut blog small batch kickstarter ennui squid selfies chambray kinfolk cold-pressed vinyl. Vice listicle bitters lo-fi. Stumptown YOLO intelligentsia bespoke +1. Swag scenester green juice narwhal sustainable.",

  "Jean shorts glossier kale chips migas subway tile seitan tote bag cloud bread, fixie franzen. Banjo roof party offal hexagon VHS chambray. Cronut crucifix subway tile bicycle rights art party, stumptown kale chips thundercats austin pitchfork you probably haven't heard of them. Etsy hella you probably haven't heard of them swag twee, chia tattooed biodiesel pok pok.",

  "Selfies twee umami keffiyeh kogi heirloom truffaut. Bitters beard pabst hot chicken listicle ethical pok pok bushwick irony cardigan 90's kinfolk tote bag. Umami mixtape disrupt, portland chia gentrify sriracha pork belly woke organic tote bag seitan man bun poutine small batch. Seitan yuccie flexitarian stumptown portland plaid. Art party blog enamel pin lumbersexual pabst etsy. Cloud bread fashion axe banjo next level kinfolk cold-pressed poutine kitsch keytar PBR&B. Tumblr cold-pressed twee, DIY deep v hot chicken readymade kinfolk.",

  "Yr drinking vinegar ugh selfies stumptown locavore. Vinyl you probably haven't heard of them plaid retro, drinking vinegar man braid twee la croix coloring book vegan kickstarter street art. Cardigan tote bag locavore hoodie freegan banh mi poke. Normcore DIY mixtape cliche. Twee franzen heirloom, hell of austin blue bottle cardigan subway tile pickled vegan tumblr normcore paleo vexillologist. Pitchfork mustache viral af tofu. Bushwick chartreuse street art poke 90's marfa pug etsy coloring book post-ironic synth twee freegan pickled.",
];
